from pymongo import MongoClient

WTF_CSRF_ENABLED = True
SECRET_KEY = 'admin'
DB_NAME = 'mydatabase'

DATABASE = MongoClient()[DB_NAME]
#POSTS_COLLECTION = DATABASE.posts
STUDENT_COLLECTION = DATABASE.student
TEACHER_COLLECTION = DATABASE.teacher
ADMIN_COLLECTION = DATABASE.admin
ANCHOR_COLLECTION = DATABASE.anchor
SETTINGS_COLLECTION = DATABASE.settings

DEBUG = True
